[package]
name = "rust_guitar_app"
version = "0.1.0"
edition = "2021"

[dependencies]
console_error_panic_hook = "0.1.7"
web-sys = { version = "0.3", features = ["console"] }
leptos = { version = "0.7.7", features = ["csr"] }
leptos_meta = { version = "0.7" }
leptos_router = { version = "0.7" }
leptos-use = "0.15.6"

[[example]]
name = "playground"
path = "example/playground.rs"
