[package]
name = "leptos_stuff"
version = "0.1.0"
edition = "2021"

[dependencies]
console_error_panic_hook = "0.1.7"
leptos = { version = "0.7.7", features = ["csr"] }

[[example]]
name = "playground"
path = "example/playground.rs"